"""replace description with lineup and add official link

Revision ID: 23b11971c202
Revises: e132d70636f1
Create Date: 2026-03-23 14:40:00.479133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b11971c202'
down_revision: Union[str, Sequence[str], None] = 'e132d70636f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lineup', sa.Text(), nullable=False))
    op.add_column('events', sa.Column('official_link', sa.String(length=500), nullable=True))
    op.drop_column('events', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.TEXT(), nullable=False))
    op.drop_column('events', 'official_link')
    op.drop_column('events', 'lineup')
    # ### end Alembic commands ###
