"""remove genre from events

Revision ID: b9cbadc4bbe9
Revises: 47590e4ecd49
Create Date: 2026-03-23 15:50:11.618480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cbadc4bbe9'
down_revision: Union[str, Sequence[str], None] = '47590e4ecd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('genre', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
