"""update event datetime fields

Revision ID: e132d70636f1
Revises: 538e29b9c784
Create Date: 2026-03-20 13:21:42.147402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e132d70636f1'
down_revision: Union[str, Sequence[str], None] = '538e29b9c784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_datetime', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    op.drop_column('events', 'max_participants')
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', sa.DATETIME(), nullable=False))
    op.add_column('events', sa.Column('max_participants', sa.INTEGER(), nullable=True))
    op.drop_column('events', 'end_datetime')
    op.drop_column('events', 'start_datetime')
    # ### end Alembic commands ###
